### ISSUE TITLE
How to Migrate table Schema

### ISSUE THREAD

**Issue by zhiephie** [codecasts/codecasts#35]

**Comment by hernandev** [comment]
Hi @zhiephie, right now this project is a little bit hard to install, some changes would be needed to a complete fork to work.

For exeperimental use, when migrating the tables, you need to use the command:

```
php artisan migrator
```

instead of `migrate`, since it's using a 3rd part package for namespaces migrations (https://github.com/artesaos/migrator)

**Comment by zhiephie** [comment]
Thanks @hernandev
